### ISSUE TITLE
Questions about pretrain

### ISSUE THREAD

**Issue by tianyumyum** [Spico197/CatalogExtraction#1]
Hello, where can I get /data4/tzhu/bert_pretrained_models/hfl_rbt3 and data/wiki_plm_4w, please? Do I need to pretrain the wiki data by myself?
    f"We couldn't connect to '{HUGGINGFACE_CO_RESOLVE_ENDPOINT}' to load this file, couldn't find it in the"
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like data/wiki_plm_4w is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
+ exit

**Comment by Spico197** [comment]
Hi there.
- `hfl_rbt3` is a distilled BERT model in Chinese, and you can find it from https://huggingface.co/hfl/rbt3  . The `plm_dir` refers to a local directory containing the downloaded model weights.
- The pretrained model (`data/wiki_plm_4w`) can be found here: https://github.com/Spico197/CatalogExtraction/releases/tag/model-v1

**Comment by tianyumyum** [comment]
Thank you！ It has been solved successfully.
