### ISSUE TITLE
Error of Inference

### ISSUE THREAD

**Issue by pjw-cmd** [Spico197/CatalogExtraction#4]
Thank you for your contribution.After I perform the directory structure of the model training, the output directory for CatalogExtraction/outputs_papers.
![image](https://github.com/Spico197/CatalogExtraction/assets/54304687/35f539b5-b661-4e9f-8f96-2fcd16609cf8)
 I began to perform inferencing.In the document suggest need to change the task_dir directory.After I changed to CatalogExtraction/outputs_papers execution error. Error message missing wiki.yaml, I transfer doc_tree_connstruction/inference/out/transducer_dataCreditEval/wiki.yaml to CatalogExtraction/outputs_papers/wiki.yaml. When I run the command again, an error message is displayed, and the error message is:
![image](https://github.com/Spico197/CatalogExtraction/assets/54304687/42694980-fddb-4efc-ae4b-1fd5b252cf94).
What should I do to perform normal inference with my model?Looking forward to your reply.Thanks.

**Comment by Spico197** [comment]
Hi there, thanks for your interest in this project. Could you please provide a detailed execution command with the detailed path? Thanks.

**Comment by Spico197** [comment]
e.g. from your file structure, the `task_dir` should be `paper_outputs/transducer_plm4w_lrscheduling_-1_CreRat_17`.

**Comment by pjw-cmd** [comment]
![image](https://github.com/Spico197/CatalogExtraction/assets/54304687/2ac2ea23-2d7f-4dbc-982c-8a7fa4bf45f8)
![image](https://github.com/Spico197/CatalogExtraction/assets/54304687/c9648251-e581-45c6-9105-37b498fa0375)

**Comment by pjw-cmd** [comment]
> e.g. from your file structure, the `task_dir` should be `paper_outputs/transducer_plm4w_lrscheduling_-1_CreRat_17`.

These are my detailed command.

**Comment by Spico197** [comment]
Hi there, thanks for you information. Could you provide the config in `paper_outputs/transducer_plm4w_lrscheduling_-1_CreRat_17/task_params.yaml` ? Normally, the program would load the `task_params.yaml` in default rather than `wiki.yaml`.

**Comment by Spico197** [comment]
Here's mine.

![image](https://github.com/Spico197/CatalogExtraction/assets/22840952/28b21826-3074-4285-afdd-932bf9bf53fa)

![image](https://github.com/Spico197/CatalogExtraction/assets/22840952/a718775a-d867-4b43-9d02-17786bb30f55)

**Comment by pjw-cmd** [comment]
> Here's mine.
> 
> ![image](https://private-user-images.githubusercontent.com/22840952/328454331-28b21826-3074-4285-afdd-932bf9bf53fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzIxMzMsIm5iZiI6MTcxNTEzMTgzMywicGF0aCI6Ii8yMjg0MDk1Mi8zMjg0NTQzMzEtMjhiMjE4MjYtMzA3NC00Mjg1LWFmZGQtOTMyYmY5YmY1M2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxMzAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YTgwODYyNzA0MTNhMTczNjEzNzUxZDQxOWIwZDUyNTE2MTU5MGYyNmYyN2JkNTlhNWFlOTEyOGVjMzc2ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AUKGggOVkMuz8OfMIgykkmvbMu2eoMWFFpy_IB-YvEw)
> 
> ![image](https://private-user-images.githubusercontent.com/22840952/328454943-a718775a-d867-4b43-9d02-17786bb30f55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzIxMzMsIm5iZiI6MTcxNTEzMTgzMywicGF0aCI6Ii8yMjg0MDk1Mi8zMjg0NTQ5NDMtYTcxODc3NWEtZDg2Ny00YjQzLTlkMDItMTc3ODZiYjMwZjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxMzAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYTU5NzAzOWJmZGQ2MzEwZTE4ZmJkZGFjY2VkMjQxMTZlMzM3MGNkODRmODI1ZTE5MmU2MWFkYmUwMGNjODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b8P-h_wtexXipRuEWWavYqYyS8iij013VsbwrVSPTXg)

**Comment by pjw-cmd** [comment]
> > Here's mine.
> > ![image](https://private-user-images.githubusercontent.com/22840952/328454331-28b21826-3074-4285-afdd-932bf9bf53fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzIxMzMsIm5iZiI6MTcxNTEzMTgzMywicGF0aCI6Ii8yMjg0MDk1Mi8zMjg0NTQzMzEtMjhiMjE4MjYtMzA3NC00Mjg1LWFmZGQtOTMyYmY5YmY1M2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxMzAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YTgwODYyNzA0MTNhMTczNjEzNzUxZDQxOWIwZDUyNTE2MTU5MGYyNmYyN2JkNTlhNWFlOTEyOGVjMzc2ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AUKGggOVkMuz8OfMIgykkmvbMu2eoMWFFpy_IB-YvEw)
> > ![image](https://private-user-images.githubusercontent.com/22840952/328454943-a718775a-d867-4b43-9d02-17786bb30f55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzIxMzMsIm5iZiI6MTcxNTEzMTgzMywicGF0aCI6Ii8yMjg0MDk1Mi8zMjg0NTQ5NDMtYTcxODc3NWEtZDg2Ny00YjQzLTlkMDItMTc3ODZiYjMwZjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxMzAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYTU5NzAzOWJmZGQ2MzEwZTE4ZmJkZGFjY2VkMjQxMTZlMzM3MGNkODRmODI1ZTE5MmU2MWFkYmUwMGNjODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b8P-h_wtexXipRuEWWavYqYyS8iij013VsbwrVSPTXg)

It worked.Thank you very much.
