### ISSUE TITLE
Concatenate text segments train problems.

### ISSUE THREAD

**Issue by pjw-cmd** [Spico197/CatalogExtraction#5]
Thank you very much for your contribution.There was a problem with it when I performed the concatenation text segment training.
![image](https://github.com/Spico197/CatalogExtraction/assets/54304687/6b6d5b51-708e-4b11-81d2-2492dd0ede5b)
![image](https://github.com/Spico197/CatalogExtraction/assets/54304687/60a7391b-2233-4d8e-bea3-a5eda8a24558)
What should be the problem?Look forward to your reply very much, thanks.

**Comment by Spico197** [comment]
Hi there, the `plm_dir` should be `/data/hfl_rbt3` instead of `/data/hfl_rbt3/pytorch_model.bin`. Please have a try with the updated PLM folder.

**Comment by pjw-cmd** [comment]
> Hi there, the `plm_dir` should be `/data/hfl_rbt3` instead of `/data/hfl_rbt3/pytorch_model.bin`. Please have a try with the updated PLM folder.
![image](https://github.com/Spico197/CatalogExtraction/assets/54304687/127086f1-e288-477d-98a3-eb464e8fa4a8)
It's still not working.

**Comment by pjw-cmd** [comment]
These are the files under my /data/hfl_rbt3
![image](https://github.com/Spico197/CatalogExtraction/assets/54304687/6385f4ab-5b1a-487f-832e-a63ce18a3484)

**Comment by Spico197** [comment]
Sorry for the late response. Based on your file structure, you should use a relative path instead of the absolute one.
Try `data/hfl_rbt3` or `./data/hfl_rbt3` instead. Besides, please make sure other paths are also relative ones.

**Comment by pjw-cmd** [comment]
> Sorry for the late response. Based on your file structure, you should use a relative path instead of the absolute one. Try `data/hfl_rbt3` or `./data/hfl_rbt3` instead. Besides, please make sure other paths are also relative ones.
Your reply is very timely.It's working, thank you very much for your help!
